version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - ./media:/app/media
      - .:/app
    env_file:
      - .env
    # NOTE: Don't use runserver in production! Use a production-ready server like gunicorn or uwsgi.
    command: >
      sh -c "python manage.py migrate &&
             gunicorn leads_project.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: leads_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
